service: api-reserva
org: danielcaballeros

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 1024
  timeout: 29
  iam:
    role: arn:aws:iam::397279833444:role/LabRole
  environment:
    TABLE_NAME_RESERVA: ${sls:stage}-tp_reserva
    LAMBDA_VALIDAR_TOKEN: api-usuarios-${sls:stage}-validar_token

functions:
  crearReserva:
    handler: crearReserva.handler
    events:
      - http:
          path: /reserva_crear
          method: post
          cors: true
          integration: lambda


  obtenerReservas:
    handler: obtenerReservas.handler
    events:
      - http:
          path: /reservas_obtener
          method: get
          cors: true
          integration: lambda

  eliminarReserva:
    handler: eliminarReserva.handler
    events:
      - http:
          path: /reserva_eliminar
          method: delete
          cors: true
          integration: lambda

resources:
  Resources:
    ReservaTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME_RESERVA}
        AttributeDefinitions:
          - AttributeName: tenant_reserva_id
            AttributeType: S
          - AttributeName: reserva_ord
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_reserva_id
            KeyType: HASH
          - AttributeName: reserva_ord
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
